<option value=""><?php echo $lang['select-country']; ?></option>
<option value="Afghanistan">Afghanistan</option>
<option value="Aland Islands">Iles Aland</option>
<option value="Albania">Albanie</option>
<option value="Algeria">Algérie</option>
<option value="American Samoa">Samoa américaines</option>
<option value="Andorra">Andorre</option>
<option value="Angola">Angola</option>
<option value="Anguilla">Anguilla</option>
<option value="Antarctica">Antarctique</option>
<option value="Antigua and Barbuda">Antigua-et-Barbuda</option>
<option value="Argentina">Argentine</option>
<option value="Armenia">Arménie</option>
<option value="Aruba">Aruba</option>
<option value="Australia">Australie</option>
<option value="Austria">Autriche</option>
<option value="Azerbaijan">Azerbaijan</option>
<option value="Bahamas">Bahamas</option>
<option value="Bahrain">Bahreïn</option>
<option value="Bangladesh">Bangladesh</option>
<option value="Barbados">Barbade</option>
<option value="Belgium">Belgique</option>
<option value="Belize">Belize</option>
<option value="Benin">Bénin</option>
<option value="Bermuda">Bermudes</option>
<option value="Bhutan">Bhoutan</option>
<option value="Belarus">Biélorussie</option>
<option value="Bolivia">Bolivie</option>
<option value="Bosnia and Herzegovina">Bosnie-Herzégovine</option>
<option value="Botswana">Botswana</option>
<option value="Bouvet Island">Ile Bouvet</option>
<option value="Brazil">Brésil</option>
<option value="British Indian Ocean Territory">Territoire britannique de l'Océan Indien</option>
<option value="Brunei Darussalam">Brunei Darussalam</option>
<option value="Bulgaria">Bulgarie</option>
<option value="Burkina Faso">Burkina Faso</option>
<option value="Burundi">Burundi</option>
<option value="Cambodia">Cambodge</option>
<option value="Cameroon">Cameroun</option>
<option value="Canada">Canada</option>
<option value="Cape Verde">Cap-Vert</option>
<option value="Cayman Islands">Iles Cayman</option>
<option value="Central African Republic">République Centrafricaine</option>
<option value="Chad">Tchad</option>
<option value="Chile">Chili</option>
<option value="China">Chine</option>
<option value="Christmas Island">Ile Christmas</option>
<option value="Cocos (Keeling) Islands">Iles des Cocos (Keeling)</option>
<option value="Colombia">Colombie</option>
<option value="Comoros">Comores</option>
<option value="Congo">Congo</option>
<option value="DR Congo">République Démocratique du Congo</option>
<option value="Cook Islands">Iles Cook</option>
<option value="Costa Rica">Costa Rica</option>
<option value="Cote D'ivoire">Côte D'Ivoire</option>
<option value="Croatia">Croatie</option>
<option value="Cuba">Cuba</option>
<option value="Cyprus">Chypre</option>
<option value="Czech Republic">Republique Tchèque</option>
<option value="Denmark">Danemark</option>
<option value="Djibouti">Djibouti</option>
<option value="Dominica">Dominique</option>
<option value="Dominican Republic">Republique Dominicaine</option>
<option value="Ecuador">Equateur</option>
<option value="Egypt">Egypte</option>
<option value="El Salvador">El Salvador</option>
<option value="Equatorial Guinea">Guinée Equatoriale</option>
<option value="Eritrea">Erythrée</option>
<option value="Estonia">Estonie</option>
<option value="Ethiopia">Ethiopie</option>
<option value="Falkland Islands (Malvinas)">Iles Falkland (Malvines)</option>
<option value="Faroe Islands">Iles Féroé</option>
<option value="Fiji">Iles Fidji</option>
<option value="Finland">Finlande</option>
<option value="France">France</option>
<option value="French Guiana">Guyanes Française</option>
<option value="French Polynesia">Polynésie Française</option>
<option value="French Southern Territories">Terres australes françaises</option>
<option value="Gabon">Gabon</option>
<option value="Gambia">Gambie</option>
<option value="Georgia">Géorgie</option>
<option value="Germany">Allemagne</option>
<option value="Ghana">Ghana</option>
<option value="Gibraltar">Gibraltar</option>
<option value="Greece">Grèce</option>
<option value="Greenland">Groenland</option>
<option value="Grenada">Grenade</option>
<option value="Guadeloupe">Guadeloupe</option>
<option value="Guam">Guam</option>
<option value="Guatemala">Guatemala</option>
<option value="Guernsey">Guernsey</option>
<option value="Guinea">Guinée</option>
<option value="Guinea-bissau">Guinée-bissau</option>
<option value="Guyana">Guyana</option>
<option value="Haiti">Haïti</option>
<option value="Heard Island and Mcdonald Islands">Iles Heard et Mcdonald</option>
<option value="Holy See (Vatican City State)">Saint-Sièrge (Cité-Etat du Vatican)</option>
<option value="Honduras">Honduras</option>
<option value="Hong Kong">Hong Kong</option>
<option value="Hungary">Hongrie</option>
<option value="Iceland">Islande</option>
<option value="India">Inde</option>
<option value="Indonesia">Indonésie</option>
<option value="Iran, Islamic Republic of">République islamique d'Iran</option>
<option value="Iraq">Iraq</option>
<option value="Ireland">Irlande</option>
<option value="Isle of Man">Man, Isle of</option>
<option value="Israel">Israël</option>
<option value="Italy">Italie</option>
<option value="Jamaica">Jamaïque</option>
<option value="Japan">Japon</option>
<option value="Jersey">Jersey</option>
<option value="Jordan">Jordanie</option>
<option value="Kazakhstan">Kazakhstan</option>
<option value="Kenya">Kenya</option>
<option value="Kiribati">Kiribati</option>
<option value="Korea, Democratic People's Republic of">République Populaire Démocratique de Corée du Sud</option>
<option value="Korea, Republic of">République de Corée du Nord</option>
<option value="Kuwait">Koweït</option>
<option value="Kyrgyzstan">Kirghizistan</option>
<option value="Lao People's Democratic Republic">République Populaire Démocratique du Laos</option>
<option value="Latvia">Lettonie</option>
<option value="Lebanon">Liban</option>
<option value="Lesotho">Lesotho</option>
<option value="Liberia">Liberia</option>
<option value="Libyan Arab Jamahiriya">Libye</option>
<option value="Liechtenstein">Liechtenstein</option>
<option value="Lithuania">Lituanie</option>
<option value="Luxembourg">Luxembourg</option>
<option value="Macao">Macao</option>
<option value="Macedonia, The Former Yugoslav Republic of">ex-République Yougoslave de Macédoine</option>
<option value="Madagascar">Madagascar</option>
<option value="Malawi">Malawi</option>
<option value="Malaysia">Malaysie</option>
<option value="Maldives">Maldives</option>
<option value="Mali">Mali</option>
<option value="Malta">Malte</option>
<option value="Marshall Islands">Iles Marshall</option>
<option value="Martinique">Martinique</option>
<option value="Mauritania">Mauritanie</option>
<option value="Mauritius">Maurice</option>
<option value="Mayotte">Mayotte</option>
<option value="Mexico">Mexique</option>
<option value="Micronesia, Federated States of">Etats fédérés de Micronésie</option>
<option value="Moldova, Republic of">République de Moldavie</option>
<option value="Monaco">Monaco</option>
<option value="Mongolia">Mongolie</option>
<option value="Montenegro">Monténégro</option>
<option value="Montserrat">Montserrat</option>
<option value="Morocco">Maroc</option>
<option value="Mozambique">Mozambique</option>
<option value="Myanmar">Birmanie</option>
<option value="Namibia">Namibie</option>
<option value="Nauru">Nauru</option>
<option value="Nepal">Népal</option>
<option value="Netherlands">Pays-Bas</option>
<option value="Netherlands Antilles">Antilles des Pays-Bas</option>
<option value="New Caledonia">Nouvelle-Calédonie</option>
<option value="New Zealand">Nouvelle-Zélande</option>
<option value="Nicaragua">Nicaragua</option>
<option value="Niger">Niger</option>
<option value="Nigeria">Nigeria</option>
<option value="Niue">Nioué</option>
<option value="Norfolk Island">Ile Norfolk</option>
<option value="Northern Mariana Islands">Iles Mariannes du Nord</option>
<option value="Norway">Norvège</option>
<option value="Oman">Oman</option>
<option value="Pakistan">Pakistan</option>
<option value="Palau">Palau</option>
<option value="Palestinian Territory, Occupied">Palestine</option>
<option value="Panama">Panama</option>
<option value="Papua New Guinea">Papouasie-Nouvelle-Guinée</option>
<option value="Paraguay">Paraguay</option>
<option value="Peru">Pérou</option>
<option value="Philippines">Philippines</option>
<option value="Pitcairn">Iles Pitcairn</option>
<option value="Poland">Pologne</option>
<option value="Portugal">Portugal</option>
<option value="Puerto Rico">Porto Rico</option>
<option value="Qatar">Qatar</option>
<option value="Reunion">Réunion</option>
<option value="Romania">Roumanie</option>
<option value="Russian Federation">Fédération de Russie</option>
<option value="Rwanda">Rwanda</option>
<option value="Saint Helena">Sainte-Hélène</option>
<option value="Saint Kitts and Nevis">Saint-Christophe-et-Niévès</option>
<option value="Saint Lucia">Sainte-Lucie</option>
<option value="Saint Pierre and Miquelon">Saint-Pierre-et-Miquelon</option>
<option value="Saint Vincent and The Grenadines">Saint-Vincent-et-les-Grenadines</option>
<option value="Samoa">Samoa</option>
<option value="San Marino">San Marino</option>
<option value="Sao Tome and Principe">Sao Tomé-et-Principe</option>
<option value="Saudi Arabia">Arabie saoudite</option>
<option value="Senegal">Sénégal</option>
<option value="Serbia">Serbie</option>
<option value="Seychelles">Seychelles</option>
<option value="Sierra Leone">Sierra Leone</option>
<option value="Singapore">Singapore</option>
<option value="Slovakia">Slovaquie</option>
<option value="Slovenia">Slovénie</option>
<option value="Solomon Islands">Iles Salomon</option>
<option value="Somalia">Somalie</option>
<option value="South Africa">Afrique du Sud</option>
<option value="South Georgia and The South Sandwich Islands">Georgie du Sud-et-Iles sud de Sandwich</option>
<option value="Spain">Espagne</option>
<option value="Sri Lanka">Sri Lanka</option>
<option value="Sudan">Soudan</option>
<option value="Suriname">Suriname</option>
<option value="Svalbard and Jan Mayen">Iles Svalbard et Jan Mayen</option>
<option value="Swaziland">Swaziland</option>
<option value="Sweden">Suède</option>
<option value="Switzerland">Suisse</option>
<option value="Syrian Arab Republic">République Arabe de Syrie</option>
<option value="Taiwan, Province of China">Taiwan</option>
<option value="Tajikistan">Tadjikistan</option>
<option value="Tanzania, United Republic of">Tanzanie</option>
<option value="Thailand">Thaïlande</option>
<option value="Timor-leste">Timor-Oriental</option>
<option value="Togo">Togo</option>
<option value="Tokelau">Tokélaou</option>
<option value="Tonga">Tonga</option>
<option value="Trinidad and Tobago">Trinité-et-Tobago</option>
<option value="Tunisia">Tunisie</option>
<option value="Turkey">Turquie</option>
<option value="Turkmenistan">Turkménistan</option>
<option value="Turks and Caicos Islands">Iles Turks-et-Caicos</option>
<option value="Tuvalu">Tuvalu</option>
<option value="Uganda">Ouganda</option>
<option value="Ukraine">Ukraine</option>
<option value="United Arab Emirates">Emirates Arabes Unis</option>
<option value="United Kingdom">Royaume-Uni</option>
<option value="United States">Etats-Unis</option>
<option value="United States Minor Outlying Islands">United States Minor Outlying Islands</option>
<option value="Uruguay">Uruguay</option>
<option value="Uzbekistan">Uzbékistan</option>
<option value="Vanuatu">Vanuatu</option>
<option value="Venezuela">Venezuela</option>
<option value="Viet Nam">Viêt Nam</option>
<option value="Virgin Islands, British">Iles Vierges britanique</option>
<option value="Virgin Islands, U.S.">Iles Vierges américaines</option>
<option value="Wallis and Futuna">Wallis-et-Futuna</option>
<option value="Western Sahara">Sahara Occidental</option>
<option value="Yemen">Yémen</option>
<option value="Zambia">Zambie</option>
<option value="Zimbabwe">Zimbabwe</option>