<option value=""><?php echo $lang['select-country']; ?></option>
<option <?php selectedOption($db_nationality, "Afghanistan") ?> value="Afghanistan">Afghanistan</option>
<option <?php selectedOption($db_nationality, "Aland Islands") ?> value="Aland Islands">Iles Aland</option>
<option <?php selectedOption($db_nationality, "Albania") ?> value="Albania">Albanie</option>
<option <?php selectedOption($db_nationality, "Algeria") ?> value="Algeria">Algérie</option>
<option <?php selectedOption($db_nationality, "American Samoa") ?> value="American Samoa">Samoa américaines</option>
<option <?php selectedOption($db_nationality, "Andorra") ?> value="Andorra">Andorre</option>
<option <?php selectedOption($db_nationality, "Angola") ?> value="Angola">Angola</option>
<option <?php selectedOption($db_nationality, "Anguilla") ?> value="Anguilla">Anguilla</option>
<option <?php selectedOption($db_nationality, "Antarctica") ?> value="Antarctica">Antarctique</option>
<option <?php selectedOption($db_nationality, "Antigua and Barbuda") ?> value="Antigua and Barbuda">Antigua-et-Barbuda</option>
<option <?php selectedOption($db_nationality, "Argentina") ?> value="Argentina">Argentine</option>
<option <?php selectedOption($db_nationality, "Armenia") ?> value="Armenia">Arménie</option>
<option <?php selectedOption($db_nationality, "Aruba") ?> value="Aruba">Aruba</option>
<option <?php selectedOption($db_nationality, "Australia") ?> value="Australia">Australie</option>
<option <?php selectedOption($db_nationality, "Austria") ?> value="Austria">Autriche</option>
<option <?php selectedOption($db_nationality, "Azerbaijan") ?> value="Azerbaijan">Azerbaijan</option>
<option <?php selectedOption($db_nationality, "Bahamas") ?> value="Bahamas">Bahamas</option>
<option <?php selectedOption($db_nationality, "Bahrain") ?> value="Bahrain">Bahreïn</option>
<option <?php selectedOption($db_nationality, "Bangladesh") ?> value="Bangladesh">Bangladesh</option>
<option <?php selectedOption($db_nationality, "Barbados") ?> value="Barbados">Barbade</option>
<option <?php selectedOption($db_nationality, "Belgium") ?> value="Belgium">Belgique</option>
<option <?php selectedOption($db_nationality, "Belize") ?> value="Belize">Belize</option>
<option <?php selectedOption($db_nationality, "Benin") ?> value="Benin">Bénin</option>
<option <?php selectedOption($db_nationality, "Bermuda") ?> value="Bermuda">Bermudes</option>
<option <?php selectedOption($db_nationality, "Bhutan") ?> value="Bhutan">Bhoutan</option>
<option <?php selectedOption($db_nationality, "Belarus") ?> value="Belarus">Biélorussie</option>
<option <?php selectedOption($db_nationality, "Bolivia") ?> value="Bolivia">Bolivie</option>
<option <?php selectedOption($db_nationality, "Bosnia and Herzegovina") ?> value="Bosnia and Herzegovina">Bosnie-Herzégovine</option>
<option <?php selectedOption($db_nationality, "Botswana") ?> value="Botswana">Botswana</option>
<option <?php selectedOption($db_nationality, "Bouvet Island") ?> value="Bouvet Island">Ile Bouvet</option>
<option <?php selectedOption($db_nationality, "Brazil") ?> value="Brazil">Brésil</option>
<option <?php selectedOption($db_nationality, "British Indian Ocean Territory") ?> value="British Indian Ocean Territory">Territoire britannique de l'Océan Indien</option>
<option <?php selectedOption($db_nationality, "Brunei Darussalam") ?> value="Brunei Darussalam">Brunei Darussalam</option>
<option <?php selectedOption($db_nationality, "Bulgaria") ?> value="Bulgaria">Bulgarie</option>
<option <?php selectedOption($db_nationality, "Burkina Faso") ?> value="Burkina Faso">Burkina Faso</option>
<option <?php selectedOption($db_nationality, "Burundi") ?> value="Burundi">Burundi</option>
<option <?php selectedOption($db_nationality, "Cambodia") ?> value="Cambodia">Cambodge</option>
<option <?php selectedOption($db_nationality, "Cameroon") ?> value="Cameroon">Cameroun</option>
<option <?php selectedOption($db_nationality, "Canada") ?> value="Canada">Canada</option>
<option <?php selectedOption($db_nationality, "Cape Verde") ?> value="Cape Verde">Cap-Vert</option>
<option <?php selectedOption($db_nationality, "Cayman Islands") ?> value="Cayman Islands">Iles Cayman</option>
<option <?php selectedOption($db_nationality, "Central African Republic") ?> value="Central African Republic">République Centrafricaine</option>
<option <?php selectedOption($db_nationality, "Chad") ?> value="Chad">Tchad</option>
<option <?php selectedOption($db_nationality, "Chile") ?> value="Chile">Chili</option>
<option <?php selectedOption($db_nationality, "China") ?> value="China">Chine</option>
<option <?php selectedOption($db_nationality, "Christmas Island") ?> value="Christmas Island">Ile Christmas</option>
<option <?php selectedOption($db_nationality, "Cocos (Keeling) Islands") ?> value="Cocos (Keeling) Islands">Iles des Cocos (Keeling)</option>
<option <?php selectedOption($db_nationality, "Colombia") ?> value="Colombia">Colombie</option>
<option <?php selectedOption($db_nationality, "Comoros") ?> value="Comoros">Comores</option>
<option <?php selectedOption($db_nationality, "Congo") ?> value="Congo">Congo</option>
<option <?php selectedOption($db_nationality, "DR Congo") ?> value="DR Congo">République Démocratique du Congo</option>
<option <?php selectedOption($db_nationality, "Cook Islands") ?> value="Cook Islands">Iles Cook</option>
<option <?php selectedOption($db_nationality, "Costa Rica") ?> value="Costa Rica">Costa Rica</option>
<option <?php selectedOption($db_nationality, "ote D'ivoire") ?> value="Cote D'ivoire">Côte D'Ivoire</option>
<option <?php selectedOption($db_nationality, "Croatia") ?> value="Croatia">Croatie</option>
<option <?php selectedOption($db_nationality, "Cuba") ?> value="Cuba">Cuba</option>
<option <?php selectedOption($db_nationality, "Cyprus") ?> value="Cyprus">Chypre</option>
<option <?php selectedOption($db_nationality, "Czech Republic") ?> value="Czech Republic">République Tchèque</option>
<option <?php selectedOption($db_nationality, "Denmark") ?> value="Denmark">Danemark</option>
<option <?php selectedOption($db_nationality, "Djibouti") ?> value="Djibouti">Djibouti</option>
<option <?php selectedOption($db_nationality, "Dominica") ?> value="Dominica">Dominique</option>
<option <?php selectedOption($db_nationality, "Dominican Republic") ?> value="Dominican Republic">République Dominicaine</option>
<option <?php selectedOption($db_nationality, "Equateur") ?> value="Ecuador">Equateur</option>
<option <?php selectedOption($db_nationality, "Egypt") ?> value="Egypt">Egypte</option>
<option <?php selectedOption($db_nationality, "El Salvador") ?> value="El Salvador">El Salvador</option>
<option <?php selectedOption($db_nationality, "Equatorial Guinea") ?> value="Equatorial Guinea">Guinée Equatoriale</option>
<option <?php selectedOption($db_nationality, "Eritrea") ?> value="Eritrea">Erythrée</option>
<option <?php selectedOption($db_nationality, "Estonia") ?> value="Estonia">Estonie</option>
<option <?php selectedOption($db_nationality, "Ethiopia") ?> value="Ethiopia">Ethiopie</option>
<option <?php selectedOption($db_nationality, "Falkland Islands (Malvinas)") ?> value="Falkland Islands (Malvinas)">Iles Falkland (Malvines)</option>
<option <?php selectedOption($db_nationality, "Faroe Islands") ?> value="Faroe Islands">Iles Féroé</option>
<option <?php selectedOption($db_nationality, "Fiji") ?> value="Fiji">Iles Fidji</option>
<option <?php selectedOption($db_nationality, "Finland") ?> value="Finland">Finlande</option>
<option <?php selectedOption($db_nationality, "France") ?> value="France">France</option>
<option <?php selectedOption($db_nationality, "French Guiana") ?> value="French Guiana">Guyanes Française</option>
<option <?php selectedOption($db_nationality, "French Polynesia") ?> value="French Polynesia">Polynésie Française</option>
<option <?php selectedOption($db_nationality, "French Southern Territories") ?> value="French Southern Territories">Terres australes françaises</option>
<option <?php selectedOption($db_nationality, "Gabon") ?> value="Gabon">Gabon</option>
<option <?php selectedOption($db_nationality, "Gambia") ?> value="Gambia">Gambie</option>
<option <?php selectedOption($db_nationality, "Georgia") ?> value="Georgia">Géorgie</option>
<option <?php selectedOption($db_nationality, "Germany") ?> value="Germany">Allemagne</option>
<option <?php selectedOption($db_nationality, "Ghana") ?> value="Ghana">Ghana</option>
<option <?php selectedOption($db_nationality, "Gibraltar") ?> value="Gibraltar">Gibraltar</option>
<option <?php selectedOption($db_nationality, "Greece") ?> value="Greece">Grèce</option>
<option <?php selectedOption($db_nationality, "Greenland") ?> value="Greenland">Groenland</option>
<option <?php selectedOption($db_nationality, "Grenada") ?> value="Grenada">Grenade</option>
<option <?php selectedOption($db_nationality, "Guadeloupe") ?> value="Guadeloupe">Guadeloupe</option>
<option <?php selectedOption($db_nationality, "Guam") ?> value="Guam">Guam</option>
<option <?php selectedOption($db_nationality, "Guatemala") ?> value="Guatemala">Guatemala</option>
<option <?php selectedOption($db_nationality, "Guernsey") ?> value="Guernsey">Guernsey</option>
<option <?php selectedOption($db_nationality, "Guinea") ?> value="Guinea">Guinée</option>
<option <?php selectedOption($db_nationality, "Guinea-bissau") ?> value="Guinea-bissau">Guinée-bissau</option>
<option <?php selectedOption($db_nationality, "Guyana") ?> value="Guyana">Guyana</option>
<option <?php selectedOption($db_nationality, "Haiti") ?> value="Haiti">Haïti</option>
<option <?php selectedOption($db_nationality, "Heard Island and Mcdonald Islands") ?> value="Heard Island and Mcdonald Islands">Iles Heard et Mcdonald</option>
<option <?php selectedOption($db_nationality, "Holy See (Vatican City State)") ?> value="Holy See (Vatican City State)">Saint-Sièrge (Cité-Etat du Vatican)</option>
<option <?php selectedOption($db_nationality, "Honduras") ?> value="Honduras">Honduras</option>
<option <?php selectedOption($db_nationality, "Hong Kong") ?> value="Hong Kong">Hong Kong</option>
<option <?php selectedOption($db_nationality, "Hungary") ?> value="Hungary">Hongrie</option>
<option <?php selectedOption($db_nationality, "Iceland") ?> value="Iceland">Islande</option>
<option <?php selectedOption($db_nationality, "India") ?> value="India">Inde</option>
<option <?php selectedOption($db_nationality, "Indonesia") ?> value="Indonesia">Indonésie</option>
<option <?php selectedOption($db_nationality, "Iran, Islamic Republic of") ?> value="Iran, Islamic Republic of">République islamique d'Iran</option>
<option <?php selectedOption($db_nationality, "Iraq") ?> value="Iraq">Iraq</option>
<option <?php selectedOption($db_nationality, "Ireland") ?> value="Ireland">Irlande</option>
<option <?php selectedOption($db_nationality, "Isle of Man") ?> value="Isle of Man">Man, Isle of</option>
<option <?php selectedOption($db_nationality, "Israel") ?> value="Israel">Israël</option>
<option <?php selectedOption($db_nationality, "Italy") ?> value="Italy">Italie</option>
<option <?php selectedOption($db_nationality, "Jamaica") ?> value="Jamaica">Jamaïque</option>
<option <?php selectedOption($db_nationality, "Japan") ?> value="Japan">Japon</option>
<option <?php selectedOption($db_nationality, "Jersey") ?> value="Jersey">Jersey</option>
<option <?php selectedOption($db_nationality, "Jordan") ?> value="Jordan">Jordanie</option>
<option <?php selectedOption($db_nationality, "Kazakhstan") ?> value="Kazakhstan">Kazakhstan</option>
<option <?php selectedOption($db_nationality, "Kenya") ?> value="Kenya">Kenya</option>
<option <?php selectedOption($db_nationality, "Kiribati") ?> value="Kiribati">Kiribati</option>
<option <?php selectedOption($db_nationality, "Korea, Democratic People's Republic of") ?> value="Korea, Democratic People's Republic of">République Populaire Démocratique de Corée du Sud</option>
<option <?php selectedOption($db_nationality, "Korea, Republic of") ?> value="Korea, Republic of">République de Corée du Nord</option>
<option <?php selectedOption($db_nationality, "Kuwait") ?> value="Kuwait">Koweït</option>
<option <?php selectedOption($db_nationality, "Kyrgyzstan") ?> value="Kyrgyzstan">Kirghizistan</option>
<option <?php selectedOption($db_nationality, "Lao People's Democratic Republic") ?> value="Lao People's Democratic Republic">République Populaire Démocratique du Laos</option>
<option <?php selectedOption($db_nationality, "Latvia") ?> value="Latvia">Lettonie</option>
<option <?php selectedOption($db_nationality, "Lebanon") ?> value="Lebanon">Liban</option>
<option <?php selectedOption($db_nationality, "Lesotho") ?> value="Lesotho">Lesotho</option>
<option <?php selectedOption($db_nationality, "Liberia") ?> value="Liberia">Libéria</option>
<option <?php selectedOption($db_nationality, "Libyan Arab Jamahiriya") ?> value="Libyan Arab Jamahiriya">Libye</option>
<option <?php selectedOption($db_nationality, "Liechtenstein") ?> value="Liechtenstein">Liechtenstein</option>
<option <?php selectedOption($db_nationality, "Lithuania") ?> value="Lithuania">Lituanie</option>
<option <?php selectedOption($db_nationality, "Luxembourg") ?> value="Luxembourg">Luxembourg</option>
<option <?php selectedOption($db_nationality, "Macao") ?> value="Macao">Macao</option>
<option <?php selectedOption($db_nationality, "Macedonia, The Former Yugoslav Republic of") ?> value="Macedonia, The Former Yugoslav Republic of">ex-République Yougoslave de Macédoine</option>
<option <?php selectedOption($db_nationality, "Madagascar") ?> value="Madagascar">Madagascar</option>
<option <?php selectedOption($db_nationality, "Malawi") ?> value="Malawi">Malawi</option>
<option <?php selectedOption($db_nationality, "Malaysia") ?> value="Malaysia">Malaysie</option>
<option <?php selectedOption($db_nationality, "Maldives") ?> value="Maldives">Maldives</option>
<option <?php selectedOption($db_nationality, "Mali") ?> value="Mali">Mali</option>
<option <?php selectedOption($db_nationality, "Malta") ?> value="Malta">Malte</option>
<option <?php selectedOption($db_nationality, "Marshall Islands") ?> value="Marshall Islands">Iles Marshall</option>
<option <?php selectedOption($db_nationality, "Martinique") ?> value="Martinique">Martinique</option>
<option <?php selectedOption($db_nationality, "Mauritania") ?> value="Mauritania">Mauritanie</option>
<option <?php selectedOption($db_nationality, "Mauritius") ?> value="Mauritius">Maurice</option>
<option <?php selectedOption($db_nationality, "Mayotte") ?> value="Mayotte">Mayotte</option>
<option <?php selectedOption($db_nationality, "Mexico") ?> value="Mexico">Mexique</option>
<option <?php selectedOption($db_nationality, "Micronesia, Federated States of") ?> value="Micronesia, Federated States of">Etats fédérés de Micronésie</option>
<option <?php selectedOption($db_nationality, "Moldova, Republic of") ?> value="Moldova, Republic of">République de Moldavie</option>
<option <?php selectedOption($db_nationality, "Monaco") ?> value="Monaco">Monaco</option>
<option <?php selectedOption($db_nationality, "Mongolia") ?> value="Mongolia">Mongolie</option>
<option <?php selectedOption($db_nationality, "Montenegro") ?> value="Montenegro">Monténégro</option>
<option <?php selectedOption($db_nationality, "Montserrat") ?> value="Montserrat">Montserrat</option>
<option <?php selectedOption($db_nationality, "Morocco") ?> value="Morocco">Maroc</option>
<option <?php selectedOption($db_nationality, "Mozambique") ?> value="Mozambique">Mozambique</option>
<option <?php selectedOption($db_nationality, "Myanmar") ?> value="Myanmar">Birmanie</option>
<option <?php selectedOption($db_nationality, "Namibia") ?> value="Namibia">Namibie</option>
<option <?php selectedOption($db_nationality, "Nauru") ?> value="Nauru">Nauru</option>
<option <?php selectedOption($db_nationality, "Nepal") ?> value="Nepal">Népal</option>
<option <?php selectedOption($db_nationality, "Netherlands") ?> value="Netherlands">Pays-Bas</option>
<option <?php selectedOption($db_nationality, "Netherlands Antilles") ?> value="Netherlands Antilles">Antilles des Pays-Bas</option>
<option <?php selectedOption($db_nationality, "New Caledonia") ?> value="New Caledonia">Nouvelle-Calédonie</option>
<option <?php selectedOption($db_nationality, "New Zealand") ?> value="New Zealand">Nouvelle-Zélande</option>
<option <?php selectedOption($db_nationality, "Nicaragua") ?> value="Nicaragua">Nicaragua</option>
<option <?php selectedOption($db_nationality, "Niger") ?> value="Niger">Niger</option>
<option <?php selectedOption($db_nationality, "Nigeria") ?> value="Nigeria">Nigeria</option>
<option <?php selectedOption($db_nationality, "Niue") ?> value="Niue">Nioué</option>
<option <?php selectedOption($db_nationality, "Norfolk Island") ?> value="Norfolk Island">Ile Norfolk</option>
<option <?php selectedOption($db_nationality, "Northern Mariana Islands") ?> value="Northern Mariana Islands">Iles Mariannes du Nord</option>
<option <?php selectedOption($db_nationality, "Norway") ?> value="Norway">Norvège</option>
<option <?php selectedOption($db_nationality, "Oman") ?> value="Oman">Oman</option>
<option <?php selectedOption($db_nationality, "Pakistan") ?> value="Pakistan">Pakistan</option>
<option <?php selectedOption($db_nationality, "Palau") ?> value="Palau">Palau</option>
<option <?php selectedOption($db_nationality, "Palestinian Territory, Occupied") ?> value="Palestinian Territory, Occupied">Palestine</option>
<option <?php selectedOption($db_nationality, "Panama") ?> value="Panama">Panama</option>
<option <?php selectedOption($db_nationality, "Papua New Guine") ?> value="Papua New Guinea">Papouasie-Nouvelle-Guinée</option>
<option <?php selectedOption($db_nationality, "Paraguay") ?> value="Paraguay">Paraguay</option>
<option <?php selectedOption($db_nationality, "Peru") ?> value="Peru">Pérou</option>
<option <?php selectedOption($db_nationality, "Philippines") ?> value="Philippines">Philippines</option>
<option <?php selectedOption($db_nationality, "Pitcairn") ?> value="Pitcairn">Iles Pitcairn</option>
<option <?php selectedOption($db_nationality, "Poland") ?> value="Poland">Pologne</option>
<option <?php selectedOption($db_nationality, "Portugal") ?> value="Portugal">Portugal</option>
<option <?php selectedOption($db_nationality, "Puerto Rico") ?> value="Puerto Rico">Porto Rico</option>
<option <?php selectedOption($db_nationality, "Qatar") ?> value="Qatar">Qatar</option>
<option <?php selectedOption($db_nationality, "Reunion") ?> value="Reunion">Réunion</option>
<option <?php selectedOption($db_nationality, "Romania") ?> value="Romania">Roumanie</option>
<option <?php selectedOption($db_nationality, "Russian Federation") ?> value="Russian Federation">Fédération de Russie</option>
<option <?php selectedOption($db_nationality, "Rwanda") ?> value="Rwanda">Rwanda</option>
<option <?php selectedOption($db_nationality, "Saint Helena") ?> value="Saint Helena">Sainte-Hélène</option>
<option <?php selectedOption($db_nationality, "Saint Kitts and Nevis") ?> value="Saint Kitts and Nevis">Saint-Christophe-et-Niévès</option>
<option <?php selectedOption($db_nationality, "Saint Lucia") ?> value="Saint Lucia">Sainte-Lucie</option>
<option <?php selectedOption($db_nationality, "Saint Pierre and Miquelon") ?> value="Saint Pierre and Miquelon">Saint-Pierre-et-Miquelon</option>
<option <?php selectedOption($db_nationality, "Saint Vincent and The Grenadines") ?> value="Saint Vincent and The Grenadines">Saint-Vincent-et-les-Grenadines</option>
<option <?php selectedOption($db_nationality, "Samoa") ?> value="Samoa">Samoa</option>
<option <?php selectedOption($db_nationality, "San Marino") ?> value="San Marino">San Marino</option>
<option <?php selectedOption($db_nationality, "Sao Tome and Principe") ?> value="Sao Tome and Principe">Sao Tomé-et-Principe</option>
<option <?php selectedOption($db_nationality, "Saudi Arabia") ?> value="Saudi Arabia">Arabie saoudite</option>
<option <?php selectedOption($db_nationality, "Senegal") ?> value="Senegal">Sénégal</option>
<option <?php selectedOption($db_nationality, "Serbia") ?> value="Serbia">Serbie</option>
<option <?php selectedOption($db_nationality, "Seychelles") ?> value="Seychelles">Seychelles</option>
<option <?php selectedOption($db_nationality, "Sierra Leone") ?> value="Sierra Leone">Sierra Leone</option>
<option <?php selectedOption($db_nationality, "Singapore") ?> value="Singapore">Singapore</option>
<option <?php selectedOption($db_nationality, "Slovakia") ?> value="Slovakia">Slovaquie</option>
<option <?php selectedOption($db_nationality, "Slovenia") ?> value="Slovenia">Slovénie</option>
<option <?php selectedOption($db_nationality, "Solomon Islands") ?> value="Solomon Islands">Iles Salomon</option>
<option <?php selectedOption($db_nationality, "Somalia") ?> value="Somalia">Somalie</option>
<option <?php selectedOption($db_nationality, "South Africa") ?> value="South Africa">Afrique du Sud</option>
<option <?php selectedOption($db_nationality, "South Georgia and The South Sandwich Islands") ?> value="South Georgia and The South Sandwich Islands">Georgie du Sud-et-Iles sud de Sandwich</option>
<option <?php selectedOption($db_nationality, "Spain") ?> value="Spain">Espagne</option>
<option <?php selectedOption($db_nationality, "Sri Lanka") ?> value="Sri Lanka">Sri Lanka</option>
<option <?php selectedOption($db_nationality, "Sudan") ?> value="Sudan">Soudan</option>
<option <?php selectedOption($db_nationality, "Suriname") ?> value="Suriname">Suriname</option>
<option <?php selectedOption($db_nationality, "Svalbard and Jan Mayen") ?> value="Svalbard and Jan Mayen">Iles Svalbard et Jan Mayen</option>
<option <?php selectedOption($db_nationality, "Swaziland") ?> value="Swaziland">Swaziland</option>
<option <?php selectedOption($db_nationality, "Sweden") ?> value="Sweden">Suède</option>
<option <?php selectedOption($db_nationality, "Switzerland") ?> value="Switzerland">Suisse</option>
<option <?php selectedOption($db_nationality, "Syrian Arab Republic") ?> value="Syrian Arab Republic">République Arabe de Syrie</option>
<option <?php selectedOption($db_nationality, "Taiwan, Province of China") ?> value="Taiwan, Province of China">Taiwan</option>
<option <?php selectedOption($db_nationality, "Tajikistan") ?> value="Tajikistan">Tadjikistan</option>
<option <?php selectedOption($db_nationality, "Tanzania, United Republic of") ?> value="Tanzania, United Republic of">Tanzanie</option>
<option <?php selectedOption($db_nationality, "Thailand") ?> value="Thailand">Thaïlande</option>
<option <?php selectedOption($db_nationality, "Timor-leste") ?> value="Timor-leste">Timor-Oriental</option>
<option <?php selectedOption($db_nationality, "Togo") ?> value="Togo">Togo</option>
<option <?php selectedOption($db_nationality, "Tokelau") ?> value="Tokelau">Tokélaou</option>
<option <?php selectedOption($db_nationality, "Tonga") ?> value="Tonga">Tonga</option>
<option <?php selectedOption($db_nationality, "Trinidad and Tobago") ?> value="Trinidad and Tobago">Trinité-et-Tobago</option>
<option <?php selectedOption($db_nationality, "Tunisia") ?> value="Tunisia">Tunisie</option>
<option <?php selectedOption($db_nationality, "Turkey") ?> value="Turkey">Turquie</option>
<option <?php selectedOption($db_nationality, "Turkmenistan") ?> value="Turkmenistan">Turkménistan</option>
<option <?php selectedOption($db_nationality, "Turks and Caicos Islands") ?> value="Turks and Caicos Islands">Iles Turks-et-Caicos</option>
<option <?php selectedOption($db_nationality, "Tuvalu") ?> value="Tuvalu">Tuvalu</option>
<option <?php selectedOption($db_nationality, "Uganda") ?> value="Uganda">Ouganda</option>
<option <?php selectedOption($db_nationality, "Ukraine") ?> value="Ukraine">Ukraine</option>
<option <?php selectedOption($db_nationality, "United Arab Emirates") ?> value="United Arab Emirates">Emirates Arabes Unis</option>
<option <?php selectedOption($db_nationality, "United Kingdom") ?> value="United Kingdom">Royaume-Uni</option>
<option <?php selectedOption($db_nationality, "United States") ?> value="United States">Etats-Unis</option>
<option <?php selectedOption($db_nationality, "United States Minor Outlying Islands") ?> value="United States Minor Outlying Islands">United States Minor Outlying Islands</option>
<option <?php selectedOption($db_nationality, "Uruguay") ?> value="Uruguay">Uruguay</option>
<option <?php selectedOption($db_nationality, "Uzbekistan") ?> value="Uzbekistan">Uzbékistan</option>
<option <?php selectedOption($db_nationality, "Vanuatu") ?> value="Vanuatu">Vanuatu</option>
<option <?php selectedOption($db_nationality, "Venezuela") ?> value="Venezuela">Venezuela</option>
<option <?php selectedOption($db_nationality, "Viet Nam") ?> value="Viet Nam">Viêt Nam</option>
<option <?php selectedOption($db_nationality, "Virgin Islands, British") ?> value="Virgin Islands, British">Iles Vierges britanique</option>
<option <?php selectedOption($db_nationality, "Virgin Islands, U.S.") ?> value="Virgin Islands, U.S.">Iles Vierges américaines</option>
<option <?php selectedOption($db_nationality, "Wallis and Futuna") ?> value="Wallis and Futuna">Wallis-et-Futuna</option>
<option <?php selectedOption($db_nationality, "Western Sahara") ?> value="Western Sahara">Sahara Occidental</option>
<option <?php selectedOption($db_nationality, "Yemen") ?> value="Yemen">Yémen</option>
<option <?php selectedOption($db_nationality, "Zambia") ?> value="Zambia">Zambie</option>
<option <?php selectedOption($db_nationality, "Zimbabwe") ?> value="Zimbabwe">Zimbabwe</option>