<option value=""><?php echo $lang['select-country']; ?></option>
<option <?php selectedOption($db_nationality, "Afghanistan") ?> value="Afghanistan">Afghanistan</option>
<option <?php selectedOption($db_nationality, "Aland Islands") ?> value="Aland Islands">Aland Islands</option>
<option <?php selectedOption($db_nationality, "Albania") ?> value="Albania">Albania</option>
<option <?php selectedOption($db_nationality, "Algeria") ?> value="Algeria">Algeria</option>
<option <?php selectedOption($db_nationality, "American Samoa") ?> value="American Samoa">American Samoa</option>
<option <?php selectedOption($db_nationality, "Andorra") ?> value="Andorra">Andorra</option>
<option <?php selectedOption($db_nationality, "Angola") ?> value="Angola">Angola</option>
<option <?php selectedOption($db_nationality, "Anguilla") ?> value="Anguilla">Anguilla</option>
<option <?php selectedOption($db_nationality, "Antarctica") ?> value="Antarctica">Antarctica</option>
<option <?php selectedOption($db_nationality, "Antigua and Barbuda") ?> value="Antigua and Barbuda">Antigua and Barbuda</option>
<option <?php selectedOption($db_nationality, "Argentina") ?> value="Argentina">Argentina</option>
<option <?php selectedOption($db_nationality, "Armenia") ?> value="Armenia">Armenia</option>
<option <?php selectedOption($db_nationality, "Aruba") ?> value="Aruba">Aruba</option>
<option <?php selectedOption($db_nationality, "Australia") ?> value="Australia">Australia</option>
<option <?php selectedOption($db_nationality, "Austria") ?> value="Austria">Austria</option>
<option <?php selectedOption($db_nationality, "Azerbaijan") ?> value="Azerbaijan">Azerbaijan</option>
<option <?php selectedOption($db_nationality, "Bahamas") ?> value="Bahamas">Bahamas</option>
<option <?php selectedOption($db_nationality, "Bahrain") ?> value="Bahrain">Bahrain</option>
<option <?php selectedOption($db_nationality, "Bangladesh") ?> value="Bangladesh">Bangladesh</option>
<option <?php selectedOption($db_nationality, "Barbados") ?> value="Barbados">Barbados</option>
<option <?php selectedOption($db_nationality, "Belarus") ?> value="Belarus">Belarus</option>
<option <?php selectedOption($db_nationality, "Belgium") ?> value="Belgium">Belgium</option>
<option <?php selectedOption($db_nationality, "Belize") ?> value="Belize">Belize</option>
<option <?php selectedOption($db_nationality, "Benin") ?> value="Benin">Benin</option>
<option <?php selectedOption($db_nationality, "Bermuda") ?> value="Bermuda">Bermuda</option>
<option <?php selectedOption($db_nationality, "Bhutan") ?> value="Bhutan">Bhutan</option>
<option <?php selectedOption($db_nationality, "Bolivia") ?> value="Bolivia">Bolivia</option>
<option <?php selectedOption($db_nationality, "Bosnia and Herzegovina") ?> value="Bosnia and Herzegovina">Bosnia and Herzegovina</option>
<option <?php selectedOption($db_nationality, "Botswana") ?> value="Botswana">Botswana</option>
<option <?php selectedOption($db_nationality, "Bouvet Island") ?> value="Bouvet Island">Bouvet Island</option>
<option <?php selectedOption($db_nationality, "Brazil") ?> value="Brazil">Brazil</option>
<option <?php selectedOption($db_nationality, "British Indian Ocean Territory") ?> value="British Indian Ocean Territory">British Indian Ocean Territory</option>
<option <?php selectedOption($db_nationality, "Brunei Darussalam") ?> value="Brunei Darussalam">Brunei Darussalam</option>
<option <?php selectedOption($db_nationality, "Bulgaria") ?> value="Bulgaria">Bulgaria</option>
<option <?php selectedOption($db_nationality, "Burkina Faso") ?> value="Burkina Faso">Burkina Faso</option>
<option <?php selectedOption($db_nationality, "Burundi") ?> value="Burundi">Burundi</option>
<option <?php selectedOption($db_nationality, "Cambodia") ?> value="Cambodia">Cambodia</option>
<option <?php selectedOption($db_nationality, "Cameroon") ?> value="Cameroon">Cameroon</option>
<option <?php selectedOption($db_nationality, "Canada") ?> value="Canada">Canada</option>
<option <?php selectedOption($db_nationality, "Cape Verde") ?> value="Cape Verde">Cape Verde</option>
<option <?php selectedOption($db_nationality, "Cayman Islands") ?> value="Cayman Islands">Cayman Islands</option>
<option <?php selectedOption($db_nationality, "Central African Republic") ?> value="Central African Republic">Central African Republic</option>
<option <?php selectedOption($db_nationality, "Chad") ?> value="Chad">Chad</option>
<option <?php selectedOption($db_nationality, "Chile") ?> value="Chile">Chile</option>
<option <?php selectedOption($db_nationality, "China") ?>value="China">China</option>
<option <?php selectedOption($db_nationality, "Christmas Island") ?> value="Christmas Island">Christmas Island</option>
<option <?php selectedOption($db_nationality, "Cocos (Keeling) Islands") ?> value="Cocos (Keeling) Islands">Cocos (Keeling) Islands</option>
<option <?php selectedOption($db_nationality, "Colombia") ?> value="Colombia">Colombia</option>
<option <?php selectedOption($db_nationality, "Comoros") ?> value="Comoros">Comoros</option>
<option <?php selectedOption($db_nationality, "Congo") ?> value="Congo">Congo</option>
<option <?php selectedOption($db_nationality, "DR Congo") ?> value="DR Congo">Congo, The Democratic Republic of The</option>
<option <?php selectedOption($db_nationality, "Cook Islands") ?> value="Cook Islands">Cook Islands</option>
<option <?php selectedOption($db_nationality, "Costa Rica") ?> value="Costa Rica">Costa Rica</option>
<option <?php selectedOption($db_nationality, "Cote D'ivoire") ?> value="Cote D'ivoire">Cote D'ivoire</option>
<option <?php selectedOption($db_nationality, "Croatia") ?> value="Croatia">Croatia</option>
<option <?php selectedOption($db_nationality, "Cuba") ?> value="Cuba">Cuba</option>
<option <?php selectedOption($db_nationality, "Cyprus") ?> value="Cyprus">Cyprus</option>
<option <?php selectedOption($db_nationality, "Czech Republic") ?> value="Czech Republic">Czech Republic</option>
<option <?php selectedOption($db_nationality, "Denmark") ?> value="Denmark">Denmark</option>
<option <?php selectedOption($db_nationality, "Djibouti") ?> value="Djibouti">Djibouti</option>
<option <?php selectedOption($db_nationality, "Dominica") ?> value="Dominica">Dominica</option>
<option <?php selectedOption($db_nationality, "Dominican Republic") ?> value="Dominican Republic">Dominican Republic</option>
<option <?php selectedOption($db_nationality, "Ecuador") ?> value="Ecuador">Ecuador</option>
<option <?php selectedOption($db_nationality, "Egypt") ?> value="Egypt">Egypt</option>
<option <?php selectedOption($db_nationality, "El Salvador") ?> value="El Salvador">El Salvador</option>
<option <?php selectedOption($db_nationality, "Equatorial Guinea") ?> value="Equatorial Guinea">Equatorial Guinea</option>
<option <?php selectedOption($db_nationality, "Eritrea") ?> value="Eritrea">Eritrea</option>
<option <?php selectedOption($db_nationality, "Estonia") ?> value="Estonia">Estonia</option>
<option <?php selectedOption($db_nationality, "Ethiopia") ?> value="Ethiopia">Ethiopia</option>
<option <?php selectedOption($db_nationality, "Falkland Islands (Malvinas)") ?> value="Falkland Islands (Malvinas)">Falkland Islands (Malvinas)</option>
<option <?php selectedOption($db_nationality, "Faroe Islands") ?> value="Faroe Islands">Faroe Islands</option>
<option <?php selectedOption($db_nationality, "Fiji") ?> value="Fiji">Fiji</option>
<option <?php selectedOption($db_nationality, "Finland") ?> value="Finland">Finland</option>
<option <?php selectedOption($db_nationality, "France") ?> value="France">France</option>
<option <?php selectedOption($db_nationality, "French Guiana") ?> value="French Guiana">French Guiana</option>
<option <?php selectedOption($db_nationality, "French Polynesia") ?> value="French Polynesia">French Polynesia</option>
<option <?php selectedOption($db_nationality, "French Southern Territories") ?> value="French Southern Territories">French Southern Territories</option>
<option <?php selectedOption($db_nationality, "Gabon") ?> value="Gabon">Gabon</option>
<option <?php selectedOption($db_nationality, "Gambia") ?> value="Gambia">Gambia</option>
<option <?php selectedOption($db_nationality, "Georgia") ?> value="Georgia">Georgia</option>
<option <?php selectedOption($db_nationality, "Germany") ?> value="Germany">Germany</option>
<option <?php selectedOption($db_nationality, "Ghana") ?> value="Ghana">Ghana</option>
<option <?php selectedOption($db_nationality, "Gibraltar") ?> value="Gibraltar">Gibraltar</option>
<option <?php selectedOption($db_nationality, "Greece") ?> value="Greece">Greece</option>
<option <?php selectedOption($db_nationality, "Greenland") ?> value="Greenland">Greenland</option>
<option <?php selectedOption($db_nationality, "Grenada") ?> value="Grenada">Grenada</option>
<option <?php selectedOption($db_nationality, "Guadeloupe") ?> value="Guadeloupe">Guadeloupe</option>
<option <?php selectedOption($db_nationality, "Guam") ?> value="Guam">Guam</option>
<option <?php selectedOption($db_nationality, "Guatemala") ?> value="Guatemala">Guatemala</option>
<option <?php selectedOption($db_nationality, "Guernsey") ?> value="Guernsey">Guernsey</option>
<option <?php selectedOption($db_nationality, "Guinea") ?> value="Guinea">Guinea</option>
<option <?php selectedOption($db_nationality, "Guinea-bissau") ?> value="Guinea-bissau">Guinea-bissau</option>
<option <?php selectedOption($db_nationality, "Guyana") ?> value="Guyana">Guyana</option>
<option <?php selectedOption($db_nationality, "Haiti") ?> value="Haiti">Haiti</option>
<option <?php selectedOption($db_nationality, "Heard Island and Mcdonald Islands") ?> value="Heard Island and Mcdonald Islands">Heard Island and Mcdonald Islands</option>
<option <?php selectedOption($db_nationality, "Holy See (Vatican City State)") ?> value="Holy See (Vatican City State)">Holy See (Vatican City State)</option>
<option <?php selectedOption($db_nationality, "Honduras") ?> value="Honduras">Honduras</option>
<option <?php selectedOption($db_nationality, "Hong Kong") ?> value="Hong Kong">Hong Kong</option>
<option <?php selectedOption($db_nationality, "Hungary") ?> value="Hungary">Hungary</option>
<option <?php selectedOption($db_nationality, "Iceland") ?> value="Iceland">Iceland</option>
<option <?php selectedOption($db_nationality, "India") ?> value="India">India</option>
<option <?php selectedOption($db_nationality, "Indonesia") ?> value="Indonesia">Indonesia</option>
<option <?php selectedOption($db_nationality, "Iran, Islamic Republic of") ?> value="Iran, Islamic Republic of">Iran, Islamic Republic of</option>
<option <?php selectedOption($db_nationality, "Iraq") ?> value="Iraq">Iraq</option>
<option <?php selectedOption($db_nationality, "Ireland") ?> value="Ireland">Ireland</option>
<option <?php selectedOption($db_nationality, "Isle of Man") ?> value="Isle of Man">Isle of Man</option>
<option <?php selectedOption($db_nationality, "Israel") ?> value="Israel">Israel</option>
<option <?php selectedOption($db_nationality, "Italy") ?> value="Italy">Italy</option>
<option <?php selectedOption($db_nationality, "Jamaica") ?> value="Jamaica">Jamaica</option>
<option <?php selectedOption($db_nationality, "Japan") ?> value="Japan">Japan</option>
<option <?php selectedOption($db_nationality, "Jersey") ?> value="Jersey">Jersey</option>
<option <?php selectedOption($db_nationality, "Jordan") ?> value="Jordan">Jordan</option>
<option <?php selectedOption($db_nationality, "Kazakhstan") ?> value="Kazakhstan">Kazakhstan</option>
<option <?php selectedOption($db_nationality, "Kenya") ?> value="Kenya">Kenya</option>
<option <?php selectedOption($db_nationality, "Kiribati") ?> value="Kiribati">Kiribati</option>
<option <?php selectedOption($db_nationality, "Korea, Democratic People's Republic of") ?> value="Korea, Democratic People's Republic of">Korea, Democratic People's Republic of</option>
<option <?php selectedOption($db_nationality, "Korea, Republic of") ?> value="Korea, Republic of">Korea, Republic of</option>
<option <?php selectedOption($db_nationality, "Kuwait") ?> value="Kuwait">Kuwait</option>
<option <?php selectedOption($db_nationality, "Kyrgyzstan") ?> value="Kyrgyzstan">Kyrgyzstan</option>
<option <?php selectedOption($db_nationality, "Lao People's Democratic Republic") ?> value="Lao People's Democratic Republic">Lao People's Democratic Republic</option>
<option <?php selectedOption($db_nationality, "Latvia") ?> value="Latvia">Latvia</option>
<option <?php selectedOption($db_nationality, "Lesotho") ?> value="Lebanon">Lebanon</option>
<option <?php selectedOption($db_nationality, "Afghanistan") ?> value="Lesotho">Lesotho</option>
<option <?php selectedOption($db_nationality, "Liberia") ?> value="Liberia">Liberia</option>
<option <?php selectedOption($db_nationality, "Libyan Arab Jamahiriya") ?> value="Libyan Arab Jamahiriya">Libyan Arab Jamahiriya</option>
<option <?php selectedOption($db_nationality, "Liechtenstein") ?> value="Liechtenstein">Liechtenstein</option>
<option <?php selectedOption($db_nationality, "Lithuania") ?> value="Lithuania">Lithuania</option>
<option <?php selectedOption($db_nationality, "Luxembourg") ?> value="Luxembourg">Luxembourg</option>
<option <?php selectedOption($db_nationality, "Macao") ?> value="Macao">Macao</option>
<option <?php selectedOption($db_nationality, "Macedonia, The Former Yugoslav Republic of") ?> value="Macedonia, The Former Yugoslav Republic of">Macedonia, The Former Yugoslav Republic of</option>
<option <?php selectedOption($db_nationality, "Madagascar") ?> value="Madagascar">Madagascar</option>
<option <?php selectedOption($db_nationality, "Malawi") ?> value="Malawi">Malawi</option>
<option <?php selectedOption($db_nationality, "Malaysia") ?> value="Malaysia">Malaysia</option>
<option <?php selectedOption($db_nationality, "Maldives") ?> value="Maldives">Maldives</option>
<option <?php selectedOption($db_nationality, "Mali") ?> value="Mali">Mali</option>
<option <?php selectedOption($db_nationality, "Malta") ?> value="Malta">Malta</option>
<option <?php selectedOption($db_nationality, "Marshall Islands") ?> value="Marshall Islands">Marshall Islands</option>
<option <?php selectedOption($db_nationality, "Martinique") ?> value="Martinique">Martinique</option>
<option <?php selectedOption($db_nationality, "Mauritania") ?> value="Mauritania">Mauritania</option>
<option <?php selectedOption($db_nationality, "Mauritius") ?> value="Mauritius">Mauritius</option>
<option <?php selectedOption($db_nationality, "Mayotte") ?> value="Mayotte">Mayotte</option>
<option <?php selectedOption($db_nationality, "Mexico") ?> value="Mexico">Mexico</option>
<option <?php selectedOption($db_nationality, "Micronesia, Federated States of") ?> value="Micronesia, Federated States of">Micronesia, Federated States of</option>
<option <?php selectedOption($db_nationality, "Moldova, Republic of") ?> value="Moldova, Republic of">Moldova, Republic of</option>
<option <?php selectedOption($db_nationality, "Monaco") ?> value="Monaco">Monaco</option>
<option <?php selectedOption($db_nationality, "Mongolia") ?> value="Mongolia">Mongolia</option>
<option <?php selectedOption($db_nationality, "Montenegro") ?> value="Montenegro">Montenegro</option>
<option <?php selectedOption($db_nationality, "Montserrat") ?> value="Montserrat">Montserrat</option>
<option <?php selectedOption($db_nationality, "Morocco") ?> value="Morocco">Morocco</option>
<option <?php selectedOption($db_nationality, "Mozambique") ?> value="Mozambique">Mozambique</option>
<option <?php selectedOption($db_nationality, "Myanmar") ?> value="Myanmar">Myanmar</option>
<option <?php selectedOption($db_nationality, "Namibia") ?> value="Namibia">Namibia</option>
<option <?php selectedOption($db_nationality, "Nauru") ?> value="Nauru">Nauru</option>
<option <?php selectedOption($db_nationality, "Nepal") ?> value="Nepal">Nepal</option>
<option <?php selectedOption($db_nationality, "Netherlands") ?> value="Netherlands">Netherlands</option>
<option <?php selectedOption($db_nationality, "Netherlands Antilles") ?> value="Netherlands Antilles">Netherlands Antilles</option>
<option <?php selectedOption($db_nationality, "New Caledonia") ?> value="New Caledonia">New Caledonia</option>
<option <?php selectedOption($db_nationality, "New Zealand") ?> value="New Zealand">New Zealand</option>
<option <?php selectedOption($db_nationality, "Nicaragua") ?> value="Nicaragua">Nicaragua</option>
<option <?php selectedOption($db_nationality, "Niger") ?> value="Niger">Niger</option>
<option <?php selectedOption($db_nationality, "Nigeria") ?> value="Nigeria">Nigeria</option>
<option <?php selectedOption($db_nationality, "Niue") ?> value="Niue">Niue</option>
<option <?php selectedOption($db_nationality, "Norfolk Island") ?> value="Norfolk Island">Norfolk Island</option>
<option <?php selectedOption($db_nationality, "Northern Mariana Islands") ?> value="Northern Mariana Islands">Northern Mariana Islands</option>
<option <?php selectedOption($db_nationality, "Norway") ?> value="Norway">Norway</option>
<option <?php selectedOption($db_nationality, "Oman") ?> value="Oman">Oman</option>
<option <?php selectedOption($db_nationality, "Pakistan") ?> value="Pakistan">Pakistan</option>
<option <?php selectedOption($db_nationality, "Palau") ?> value="Palau">Palau</option>
<option <?php selectedOption($db_nationality, "Palestinian Territory, Occupied") ?> value="Palestinian Territory, Occupied">Palestinian Territory, Occupied</option>
<option <?php selectedOption($db_nationality, "Panama") ?> value="Panama">Panama</option>
<option <?php selectedOption($db_nationality, "Papua New Guinea") ?> value="Papua New Guinea">Papua New Guinea</option>
<option <?php selectedOption($db_nationality, "Paraguay") ?> value="Paraguay">Paraguay</option>
<option <?php selectedOption($db_nationality, "Peru") ?> value="Peru">Peru</option>
<option <?php selectedOption($db_nationality, "Philippines") ?> value="Philippines">Philippines</option>
<option <?php selectedOption($db_nationality, "Pitcairn") ?> value="Pitcairn">Pitcairn</option>
<option <?php selectedOption($db_nationality, "Poland") ?> value="Poland">Poland</option>
<option <?php selectedOption($db_nationality, "Portugal") ?> value="Portugal">Portugal</option>
<option <?php selectedOption($db_nationality, "Puerto Rico") ?> value="Puerto Rico">Puerto Rico</option>
<option <?php selectedOption($db_nationality, "Qatar") ?> value="Qatar">Qatar</option>
<option <?php selectedOption($db_nationality, "Reunion") ?> value="Reunion">Reunion</option>
<option <?php selectedOption($db_nationality, "Romania") ?> value="Romania">Romania</option>
<option <?php selectedOption($db_nationality, "Russian Federation") ?> value="Russian Federation">Russian Federation</option>
<option <?php selectedOption($db_nationality, "Rwanda") ?> value="Rwanda">Rwanda</option>
<option <?php selectedOption($db_nationality, "Saint Helena") ?> value="Saint Helena">Saint Helena</option>
<option <?php selectedOption($db_nationality, "Saint Kitts and Nevis") ?> value="Saint Kitts and Nevis">Saint Kitts and Nevis</option>
<option <?php selectedOption($db_nationality, "Saint Lucia") ?> value="Saint Lucia">Saint Lucia</option>
<option <?php selectedOption($db_nationality, "Saint Pierre and Miquelon") ?> value="Saint Pierre and Miquelon">Saint Pierre and Miquelon</option>
<option <?php selectedOption($db_nationality, "Saint Vincent and The Grenadines") ?> value="Saint Vincent and The Grenadines">Saint Vincent and The Grenadines</option>
<option <?php selectedOption($db_nationality, "Samoa") ?> value="Samoa">Samoa</option>
<option <?php selectedOption($db_nationality, "San Marino") ?> value="San Marino">San Marino</option>
<option <?php selectedOption($db_nationality, "Sao Tome and Principe") ?> value="Sao Tome and Principe">Sao Tome and Principe</option>
<option <?php selectedOption($db_nationality, "Saudi Arabia") ?> value="Saudi Arabia">Saudi Arabia</option>
<option <?php selectedOption($db_nationality, "Senegal") ?> value="Senegal">Senegal</option>
<option <?php selectedOption($db_nationality, "Serbia") ?> value="Serbia">Serbia</option>
<option <?php selectedOption($db_nationality, "Seychelles") ?> value="Seychelles">Seychelles</option>
<option <?php selectedOption($db_nationality, "Sierra Leone") ?> value="Sierra Leone">Sierra Leone</option>
<option <?php selectedOption($db_nationality, "Singapore") ?> value="Singapore">Singapore</option>
<option <?php selectedOption($db_nationality, "Slovakia") ?> value="Slovakia">Slovakia</option>
<option <?php selectedOption($db_nationality, "Slovenia") ?> value="Slovenia">Slovenia</option>
<option <?php selectedOption($db_nationality, "Solomon Islands") ?> value="Solomon Islands">Solomon Islands</option>
<option <?php selectedOption($db_nationality, "Somalia") ?> value="Somalia">Somalia</option>
<option <?php selectedOption($db_nationality, "South Africa") ?> value="South Africa">South Africa</option>
<option <?php selectedOption($db_nationality, "South Georgia and The South Sandwich Islands") ?> value="South Georgia and The South Sandwich Islands">South Georgia and The South Sandwich Islands</option>
<option <?php selectedOption($db_nationality, "Spain") ?> value="Spain">Spain</option>
<option <?php selectedOption($db_nationality, "Sri Lanka") ?> value="Sri Lanka">Sri Lanka</option>
<option <?php selectedOption($db_nationality, "Sudan") ?> value="Sudan">Sudan</option>
<option <?php selectedOption($db_nationality, "Suriname") ?> value="Suriname">Suriname</option>
<option <?php selectedOption($db_nationality, "Svalbard and Jan Mayen") ?> value="Svalbard and Jan Mayen">Svalbard and Jan Mayen</option>
<option <?php selectedOption($db_nationality, "Swaziland") ?> value="Swaziland">Swaziland</option>
<option <?php selectedOption($db_nationality, "Sweden") ?> value="Sweden">Sweden</option>
<option <?php selectedOption($db_nationality, "Switzerland") ?> value="Switzerland">Switzerland</option>
<option <?php selectedOption($db_nationality, "yrian Arab Republic") ?> value="Syrian Arab Republic">Syrian Arab Republic</option>
<option <?php selectedOption($db_nationality, "Taiwan, Province of China") ?> value="Taiwan, Province of China">Taiwan, Province of China</option>
<option <?php selectedOption($db_nationality, "Tajikistan") ?> value="Tajikistan">Tajikistan</option>
<option <?php selectedOption($db_nationality, "Tanzania, United Republic of") ?> value="Tanzania, United Republic of">Tanzania, United Republic of</option>
<option <?php selectedOption($db_nationality, "Thailand") ?> value="Thailand">Thailand</option>
<option <?php selectedOption($db_nationality, "Timor-leste") ?> value="Timor-leste">Timor-leste</option>
<option <?php selectedOption($db_nationality, "Togo") ?> value="Togo">Togo</option>
<option <?php selectedOption($db_nationality, "Tokelau") ?> value="Tokelau">Tokelau</option>
<option <?php selectedOption($db_nationality, "Tonga") ?> value="Tonga">Tonga</option>
<option <?php selectedOption($db_nationality, "Trinidad and Tobago") ?> value="Trinidad and Tobago">Trinidad and Tobago</option>
<option <?php selectedOption($db_nationality, "Tunisia") ?> value="Tunisia">Tunisia</option>
<option <?php selectedOption($db_nationality, "Turkey") ?> value="Turkey">Turkey</option>
<option <?php selectedOption($db_nationality, "Turkmenistan") ?> value="Turkmenistan">Turkmenistan</option>
<option <?php selectedOption($db_nationality, "Turks and Caicos Islands") ?> value="Turks and Caicos Islands">Turks and Caicos Islands</option>
<option <?php selectedOption($db_nationality, "Tuvalu") ?> value="Tuvalu">Tuvalu</option>
<option <?php selectedOption($db_nationality, "Uganda") ?> value="Uganda">Uganda</option>
<option <?php selectedOption($db_nationality, "Ukraine") ?> value="Ukraine">Ukraine</option>
<option <?php selectedOption($db_nationality, "United Arab Emirates") ?> value="United Arab Emirates">United Arab Emirates</option>
<option <?php selectedOption($db_nationality, "United Kingdom") ?> value="United Kingdom">United Kingdom</option>
<option <?php selectedOption($db_nationality, "United States") ?> value="United States">United States</option>
<option <?php selectedOption($db_nationality, "United States Minor Outlying Islands") ?> value="United States Minor Outlying Islands">United States Minor Outlying Islands</option>
<option <?php selectedOption($db_nationality, "Uruguay") ?> value="Uruguay">Uruguay</option>
<option <?php selectedOption($db_nationality, "Uzbekistan") ?> value="Uzbekistan">Uzbekistan</option>
<option <?php selectedOption($db_nationality, "Vanuatu") ?> value="Vanuatu">Vanuatu</option>
<option <?php selectedOption($db_nationality, "Venezuela") ?> value="Venezuela">Venezuela</option>
<option <?php selectedOption($db_nationality, "Viet Nam") ?> value="Viet Nam">Viet Nam</option>
<option <?php selectedOption($db_nationality, "Virgin Islands, British") ?> value="Virgin Islands, British">Virgin Islands, British</option>
<option <?php selectedOption($db_nationality, "Virgin Islands, U.S.") ?> value="Virgin Islands, U.S.">Virgin Islands, U.S.</option>
<option <?php selectedOption($db_nationality, "Wallis and Futuna") ?> value="Wallis and Futuna">Wallis and Futuna</option>
<option <?php selectedOption($db_nationality, "Western Sahara") ?> value="Western Sahara">Western Sahara</option>
<option <?php selectedOption($db_nationality, "Yemen") ?> value="Yemen">Yemen</option>
<option <?php selectedOption($db_nationality, "Zambia") ?> value="Zambia">Zambia</option>
<option <?php selectedOption($db_nationality, "Zimbabwe") ?> value="Zimbabwe">Zimbabwe</option>